import Image from 'next/image'
import React from 'react'
import ProductImagePage from '../assets/images/bedroom.jpg';
import { FilterByCategory, SortByPrice, SearchProducts, Card, ShopProducts } from '@/components';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'shop',
  description: 'Generated by create next app',
}
const page = () => {
  return (
    <>
      {/* Hero section */}
      <div>
      <div className=" ">
        <div className="absolute top-36 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center z-10">
          <h1 className="text-white text-bold">Products</h1>
        </div>
          <div className="relative w-full h-48">
            <Image src={ProductImagePage} className="w-full h-48 object-cover" alt="ProductPageImage" />
            <div className="absolute top-0 left-0 w-full h-48 bg-black bg-opacity-50 z-0"></div>
        </div>
        </div>
      </div>
      {/* Filter section */}
      <div className='mt-12 '>
        <div className='container mx-auto px-4 sm:px-6 lg:px-8'>
          <div className='flex flex-col sm:flex-row justify-between items-center'>
            <div className='mb-4 sm:mb-0'>
              <FilterByCategory />
            </div>
            <div className='flex flex-col sm:flex-row gap-4 items-center'>
              <SortByPrice />
              <SearchProducts />
            </div>
          </div>
        </div>
      </div>
      <div className='mt-15'>
        <ShopProducts/>

      </div>
    </>
    
  )
}

export default page